namespace ResellerRepository;

public interface IResellerSiteInformationPopulateRepository
{
    Task<ResellerSiteInformationPopulateResponse> ResellerSiteInformationPopulateAsync(ResellerSiteInformationPopulateRequest request);
}