namespace AutomaticTaskQueueLibrary;

public interface IAutomaticTaskQueueServiceProcessorRepository
{
    Task<AutomaticTaskQueueServiceProcessorResponse> AutomaticTaskQueueServiceProcessorAsync(AutomaticTaskQueueServiceProcessorRequest request);
}